version: '3.8'

services:
  app:
    image: golang:1.18.4
    container_name: curd-fiber-app
    ports:
      - 3005:3005
    environment:
      TZ: Asia/Tehran
    working_dir: /app
    volumes:
      - ./:/app
    command: /app/docker/command.sh
  