basePath: /
definitions:
  serializers.Login:
    properties:
      pass:
        minLength: 3
        type: string
      user:
        maxLength: 20
        minLength: 1
        type: string
    required:
    - pass
    - user
    type: object
  serializers.User:
    properties:
      email:
        type: string
      password:
        minLength: 4
        type: string
      username:
        maxLength: 20
        minLength: 1
        type: string
    required:
    - email
    - password
    - username
    type: object
host: 127.0.0.1:3005
info:
  contact:
    email: fiber@swagger.io
    name: API Support
  description: This is a  swagger for CURD Fiber
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  termsOfService: http://swagger.io/terms/
  title: CRUD Fiber
  version: "1.0"
paths:
  /api/v1/account/create:
    post:
      consumes:
      - application/json
      description: create a account
      operationId: create-account
      parameters:
      - description: User
        in: body
        name: payload
        required: true
        schema:
          $ref: '#/definitions/serializers.User'
      produces:
      - application/json
      responses:
        "200":
          description: ""
      summary: create a account
      tags:
      - account
  /api/v1/account/delete/{id}:
    delete:
      consumes:
      - application/json
      description: delete a account
      operationId: delete-account
      parameters:
      - description: User.ID
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: ""
      summary: delete a account
      tags:
      - account
  /api/v1/account/read/{id}:
    get:
      consumes:
      - application/json
      description: get string by ID
      operationId: Show-account
      parameters:
      - description: User.ID
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: ""
      summary: Show a account
      tags:
      - account
  /api/v1/account/update/{id}:
    put:
      consumes:
      - application/json
      description: update a account
      operationId: update-account
      parameters:
      - description: User
        in: body
        name: payload
        required: true
        schema:
          $ref: '#/definitions/serializers.User'
      - description: User.ID
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: ""
      summary: update a account
      tags:
      - account
  /login:
    post:
      consumes:
      - application/json
      description: create a JWT
      parameters:
      - description: Login
        in: body
        name: payload
        required: true
        schema:
          $ref: '#/definitions/serializers.Login'
      produces:
      - application/json
      responses:
        "200":
          description: ""
      summary: create a JWT
      tags:
      - authenticate
swagger: "2.0"
