basePath: /
definitions:
  serializers.User:
    properties:
      email:
        type: string
      password:
        minLength: 4
        type: string
      username:
        maxLength: 20
        minLength: 1
        type: string
    required:
    - email
    - password
    - username
    type: object
host: 127.0.0.1:3005/api/v1
info:
  contact:
    email: fiber@swagger.io
    name: API Support
  description: This is a  swagger for CURD Fiber
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  termsOfService: http://swagger.io/terms/
  title: CRUD Fiber
  version: "1.0"
paths:
  /account/create:
    post:
      consumes:
      - application/json
      description: create a account
      parameters:
      - description: User
        in: body
        name: payload
        required: true
        schema:
          $ref: '#/definitions/serializers.User'
      produces:
      - application/json
      responses:
        "200":
          description: ""
      summary: create a account
  /account/read/{id}:
    get:
      consumes:
      - application/json
      description: get string by ID
      operationId: get-string-by-int
      parameters:
      - description: User.ID
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: ""
      summary: Show a account
  /account/update/{id}:
    put:
      consumes:
      - application/json
      description: update a account
      parameters:
      - description: User
        in: body
        name: payload
        required: true
        schema:
          $ref: '#/definitions/serializers.User'
      - description: User.ID
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: ""
      summary: update a account
swagger: "2.0"
